#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -model pc104 -layout es,us -option grp:alt_shift_toggle &
$HOME/.config/bspwm/scripts/auto_start.sh &
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config focused_border_color 	"#6c7086"
bspc config normal_border_color 	"#FF00000"
bspc config focus_follows_pointer 	true
bspc config border_width         	4
bspc config window_gap          	12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 30 

### Windows Rules
bspc rule -a firefox desktop ='^2' follow=on
bspc rule -a Code    desktop ='^3' follow=on
### Floating Windows Rules
bspc rule -a TelegramDesktop state=floating follow=on
bspc rule -a Pavucontrol     state=floating
bspc rule -a Pidgin          state=floating
bspc rule -a Xdm-app          state=floating
bspc rule -a FSearch          state=floating

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


